import type { CardDef, Faction, HunterDef, Keyword, Rarity } from "./types";

export const FACTION_META: Record<
  Faction,
  { name: string; short: string; blurb: string }
> = {
  shadowborn: {
    name: "Shadowborn Spartans",
    short: "Shadowborn",
    blurb: "Bronze and night. Spears that do not miss.",
  },
  crimson: {
    name: "Crimson Horde",
    short: "Crimson",
    blurb: "Pack law. Blood pays for blood.",
  },
  abyssal: {
    name: "Abyssal Apex",
    short: "Abyssal",
    blurb: "The trench does not forgive.",
  },
  revenant: {
    name: "Vexed Revenants",
    short: "Revenants",
    blurb: "The dead still keep formation.",
  },
};

export const RARITY_LABEL: Record<Rarity, string> = {
  common: "Hunt",
  rare: "Mark",
  epic: "Apex",
  legendary: "Sovereign",
};

export const HUNTERS: Record<string, HunterDef> = {
  adamo: {
    id: "adamo",
    name: "Sparta Adamo",
    title: "First Spear",
    faction: "shadowborn",
    hp: 20,
    powerCost: 4,
    powerText: "Power strike: deal 4 to the enemy hunter.",
    powerTarget: "none",
    power: {
      kind: "rendHunter",
      n: 4,
    },
  },
  warden: {
    id: "warden",
    name: "Abyssal Warden",
    title: "Trench Crown",
    faction: "abyssal",
    hp: 20,
    powerCost: 4,
    powerText: "Power strike: deal 5 to an enemy.",
    powerTarget: "enemyAny",
    power: {
      kind: "damageTarget",
      n: 5,
    },
  },
  matriarch: {
    id: "matriarch",
    name: "Crimson Matriarch",
    title: "Blood Crest",
    faction: "crimson",
    hp: 22,
    powerCost: 4,
    powerText: "Power strike: deal 4 to the enemy hunter. Restore 3.",
    powerTarget: "none",
    power: {
      kind: "rendHunter",
      n: 4,
      heal: 3,
    },
  },
  herald: {
    id: "herald",
    name: "Vexed Herald",
    title: "Ash Crown",
    faction: "revenant",
    hp: 20,
    powerCost: 4,
    powerText: "Power strike: deal 4 to an enemy.",
    powerTarget: "enemyAny",
    power: {
      kind: "damageTarget",
      n: 4,
    },
  },
};

export const CARDS: Record<string, CardDef> = {
  "spear-initiate": {
    id: "spear-initiate",
    name: "Spear Initiate",
    faction: "shadowborn",
    type: "unit",
    rarity: "common",
    cost: 1,
    attack: 2,
    health: 1,
    keywords: ["rush"],
    text: "Rush",
    target: "none",
    collectible: true,
  },
  "night-hoplite": {
    id: "night-hoplite",
    name: "Night Hoplite",
    faction: "shadowborn",
    type: "unit",
    rarity: "common",
    cost: 2,
    attack: 2,
    health: 3,
    keywords: ["guard"],
    text: "Guard",
    target: "none",
    collectible: true,
  },
  "shadow-scout": {
    id: "shadow-scout",
    name: "Shadow Scout",
    faction: "shadowborn",
    type: "unit",
    rarity: "rare",
    cost: 2,
    attack: 3,
    health: 1,
    keywords: ["stalk"],
    text: "Stalk. Play: draw a card.",
    target: "none",
    collectible: true,
    battlecry: {
      kind: "draw",
      n: 1,
    },
  },
  "phalanx-veteran": {
    id: "phalanx-veteran",
    name: "Phalanx Veteran",
    faction: "shadowborn",
    type: "unit",
    rarity: "rare",
    cost: 3,
    attack: 2,
    health: 4,
    keywords: ["guard"],
    text: "Guard",
    target: "none",
    collectible: true,
  },
  "umbral-blade": {
    id: "umbral-blade",
    name: "Umbral Blade",
    faction: "shadowborn",
    type: "unit",
    rarity: "epic",
    cost: 3,
    attack: 4,
    health: 2,
    keywords: [],
    text: "Strike: deal 1 to the enemy hunter.",
    target: "none",
    collectible: true,
    strike: {
      kind: "damageEnemyHunter",
      n: 1,
    },
  },
  "cloaked-strategos": {
    id: "cloaked-strategos",
    name: "Cloaked Strategos",
    faction: "shadowborn",
    type: "unit",
    rarity: "epic",
    cost: 4,
    attack: 3,
    health: 5,
    keywords: [],
    text: "Play: your units get +1 / +1.",
    target: "none",
    collectible: true,
    battlecry: {
      kind: "buffAllFriendly",
      atk: 1,
      hp: 1,
    },
  },
  "aegis-of-sparta": {
    id: "aegis-of-sparta",
    name: "Aegis of Sparta",
    faction: "shadowborn",
    type: "tactic",
    rarity: "rare",
    cost: 3,
    keywords: [],
    text: "Give a friendly unit +2 / +3 and Guard.",
    target: "friendlyUnit",
    collectible: true,
    battlecry: {
      kind: "buffTarget",
      atk: 2,
      hp: 3,
      grant: ["guard"],
    },
  },
  "first-spear": {
    id: "first-spear",
    name: "The First Spear",
    faction: "shadowborn",
    type: "unit",
    rarity: "legendary",
    cost: 6,
    attack: 6,
    health: 6,
    keywords: ["apex", "overwhelm"],
    text: "Apex: after it kills, it may attack again. Overwhelm.",
    target: "none",
    collectible: true,
  },
  "blood-pup": {
    id: "blood-pup",
    name: "Blood Pup",
    faction: "crimson",
    type: "unit",
    rarity: "common",
    cost: 1,
    attack: 2,
    health: 1,
    keywords: ["pack"],
    text: "Pack: +1 Attack if you control another Crimson unit.",
    target: "none",
    collectible: true,
  },
  "pack-raptor": {
    id: "pack-raptor",
    name: "Pack Raptor",
    faction: "crimson",
    type: "unit",
    rarity: "common",
    cost: 2,
    attack: 2,
    health: 2,
    keywords: ["pack"],
    text: "Pack: +1 Attack if you control another Crimson unit.",
    target: "none",
    collectible: true,
  },
  bonebreaker: {
    id: "bonebreaker",
    name: "Bonebreaker",
    faction: "crimson",
    type: "unit",
    rarity: "rare",
    cost: 3,
    attack: 4,
    health: 2,
    keywords: ["rush", "frenzy"],
    text: "Rush. Frenzy.",
    target: "none",
    collectible: true,
  },
  "crimson-stalker": {
    id: "crimson-stalker",
    name: "Crimson Stalker",
    faction: "crimson",
    type: "unit",
    rarity: "rare",
    cost: 3,
    attack: 3,
    health: 3,
    keywords: ["stalk", "lifesteal"],
    text: "Stalk. Lifesteal.",
    target: "none",
    collectible: true,
  },
  "horned-titan": {
    id: "horned-titan",
    name: "Horned Titan",
    faction: "crimson",
    type: "unit",
    rarity: "epic",
    cost: 4,
    attack: 4,
    health: 6,
    keywords: ["guard", "overwhelm"],
    text: "Guard. Overwhelm.",
    target: "none",
    collectible: true,
  },
  "blood-frenzy": {
    id: "blood-frenzy",
    name: "Blood Frenzy",
    faction: "crimson",
    type: "tactic",
    rarity: "common",
    cost: 2,
    keywords: [],
    text: "Give a friendly unit +3 Attack this turn.",
    target: "friendlyUnit",
    collectible: true,
    battlecry: {
      kind: "tempAttackTarget",
      n: 3,
    },
  },
  stampede: {
    id: "stampede",
    name: "Stampede",
    faction: "crimson",
    type: "tactic",
    rarity: "epic",
    cost: 5,
    keywords: [],
    text: "Deal 2 to all enemy units.",
    target: "none",
    collectible: true,
    battlecry: {
      kind: "damageAllEnemyUnits",
      n: 2,
    },
  },
  "matriarch-rex": {
    id: "matriarch-rex",
    name: "Crimson Matriarch",
    faction: "crimson",
    type: "unit",
    rarity: "legendary",
    cost: 7,
    attack: 8,
    health: 8,
    keywords: ["apex", "overwhelm"],
    text: "Apex. Overwhelm. Kill: restore 4 Health.",
    target: "none",
    collectible: true,
    onKill: {
      kind: "healSelfHunter",
      n: 4,
    },
  },
  glowfin: {
    id: "glowfin",
    name: "Glowfin",
    faction: "abyssal",
    type: "unit",
    rarity: "common",
    cost: 1,
    attack: 1,
    health: 2,
    keywords: [],
    text: "Last breath: draw a card.",
    target: "none",
    collectible: true,
    deathrattle: {
      kind: "draw",
      n: 1,
    },
  },
  "tide-serpent": {
    id: "tide-serpent",
    name: "Tide Serpent",
    faction: "abyssal",
    type: "unit",
    rarity: "common",
    cost: 2,
    attack: 3,
    health: 2,
    keywords: ["cleave"],
    text: "Cleave.",
    target: "none",
    collectible: true,
    flavor: "It does not wait for the wall to break.",
  },
  "abyss-lurker": {
    id: "abyss-lurker",
    name: "Abyss Lurker",
    faction: "abyssal",
    type: "unit",
    rarity: "rare",
    cost: 3,
    attack: 2,
    health: 5,
    keywords: ["guard"],
    text: "Guard",
    target: "none",
    collectible: true,
  },
  "kraken-arm": {
    id: "kraken-arm",
    name: "Kraken Arm",
    faction: "abyssal",
    type: "unit",
    rarity: "epic",
    cost: 4,
    attack: 5,
    health: 3,
    keywords: [],
    text: "Strike: deal 1 to all enemy units.",
    target: "none",
    collectible: true,
    strike: {
      kind: "damageAllEnemyUnits",
      n: 1,
    },
  },
  "leviathan-spawn": {
    id: "leviathan-spawn",
    name: "Leviathan Spawn",
    faction: "abyssal",
    type: "unit",
    rarity: "epic",
    cost: 5,
    attack: 4,
    health: 6,
    keywords: ["retaliate", "frenzy"],
    text: "Retaliate. Frenzy.",
    target: "none",
    collectible: true,
    flavor: "The trench bites back.",
  },
  drown: {
    id: "drown",
    name: "Drown",
    faction: "abyssal",
    type: "tactic",
    rarity: "rare",
    cost: 2,
    keywords: [],
    text: "Destroy an enemy unit with 3 Health or less.",
    target: "enemyUnit",
    collectible: true,
    battlecry: {
      kind: "destroyTargetIfHpLte",
      n: 3,
    },
  },
  "tidal-surge": {
    id: "tidal-surge",
    name: "Tidal Surge",
    faction: "abyssal",
    type: "tactic",
    rarity: "rare",
    cost: 3,
    keywords: [],
    text: "Deal 2 to a unit. Draw a card.",
    target: "anyUnit",
    collectible: true,
    battlecry: {
      kind: "damageTarget",
      n: 2,
    },
  },
  "abyssal-leviathan": {
    id: "abyssal-leviathan",
    name: "Abyssal Leviathan",
    faction: "abyssal",
    type: "unit",
    rarity: "legendary",
    cost: 8,
    attack: 9,
    health: 9,
    keywords: ["guard"],
    text: "Guard",
    target: "none",
    collectible: true,
  },
  "ash-wisp": {
    id: "ash-wisp",
    name: "Ash Wisp",
    faction: "revenant",
    type: "unit",
    rarity: "common",
    cost: 1,
    attack: 1,
    health: 1,
    keywords: ["rush", "reborn"],
    text: "Rush. Reborn.",
    target: "none",
    collectible: true,
  },
  "vengeful-shade": {
    id: "vengeful-shade",
    name: "Vengeful Shade",
    faction: "revenant",
    type: "unit",
    rarity: "rare",
    cost: 2,
    attack: 2,
    health: 2,
    keywords: ["reborn"],
    text: "Reborn. Last breath: deal 2 to a random enemy.",
    target: "none",
    collectible: true,
    deathrattle: {
      kind: "randomEnemyDamage",
      n: 2,
    },
  },
  "grave-spearman": {
    id: "grave-spearman",
    name: "Grave Spearman",
    faction: "revenant",
    type: "unit",
    rarity: "common",
    cost: 3,
    attack: 3,
    health: 3,
    keywords: [],
    text: "Strike: deal 1 to the enemy hunter.",
    target: "none",
    collectible: true,
    strike: {
      kind: "damageEnemyHunter",
      n: 1,
    },
    flavor: "The dead still keep the line.",
  },
  "revenant-captain": {
    id: "revenant-captain",
    name: "Revenant Captain",
    faction: "revenant",
    type: "unit",
    rarity: "epic",
    cost: 4,
    attack: 4,
    health: 4,
    keywords: ["lifesteal"],
    text: "Lifesteal",
    target: "none",
    collectible: true,
  },
  "soul-bind": {
    id: "soul-bind",
    name: "Soul Bind",
    faction: "revenant",
    type: "tactic",
    rarity: "common",
    cost: 1,
    keywords: [],
    text: "Restore 3 Health.",
    target: "none",
    collectible: true,
    battlecry: {
      kind: "healSelfHunter",
      n: 3,
    },
  },
  "hex-vengeance": {
    id: "hex-vengeance",
    name: "Hex of Vengeance",
    faction: "revenant",
    type: "tactic",
    rarity: "rare",
    cost: 3,
    keywords: [],
    text: "Deal 3 to a unit.",
    target: "anyUnit",
    collectible: true,
    battlecry: {
      kind: "damageTarget",
      n: 3,
    },
  },
  "echo-of-war": {
    id: "echo-of-war",
    name: "Echo of War",
    faction: "revenant",
    type: "tactic",
    rarity: "epic",
    cost: 4,
    keywords: [],
    text: "Summon a 2 / 2 Shade.",
    target: "none",
    collectible: true,
    battlecry: {
      kind: "summonToken",
      tokenId: "echo-shade",
    },
  },
  "vexed-king": {
    id: "vexed-king",
    name: "The Vexed King",
    faction: "revenant",
    type: "unit",
    rarity: "legendary",
    cost: 6,
    attack: 5,
    health: 7,
    keywords: [],
    text: "When a friendly unit dies, gain +1 / +1.",
    target: "none",
    collectible: true,
    onFriendlyDeath: {
      kind: "buffTarget",
      atk: 1,
      hp: 1,
    },
  },
  "bronze-wall": {
    id: "bronze-wall",
    name: "Bronze Wall",
    faction: "shadowborn",
    type: "unit",
    rarity: "common",
    cost: 2,
    attack: 1,
    health: 5,
    keywords: ["guard", "ward"],
    text: "Guard. Ward.",
    target: "none",
    collectible: true,
    flavor: "The first spear is the shield.",
  },
  "spear-volley": {
    id: "spear-volley",
    name: "Spear Volley",
    faction: "shadowborn",
    type: "tactic",
    rarity: "rare",
    cost: 2,
    keywords: [],
    text: "Deal 2 to the enemy hunter.",
    target: "none",
    collectible: true,
    battlecry: {
      kind: "damageEnemyHunter",
      n: 2,
    },
    flavor: "Night does not miss.",
  },
  "killing-leap": {
    id: "killing-leap",
    name: "Killing Leap",
    faction: "crimson",
    type: "unit",
    rarity: "rare",
    cost: 3,
    attack: 3,
    health: 2,
    keywords: ["rush", "venom"],
    text: "Rush. Venom.",
    target: "none",
    collectible: true,
    flavor: "The pack does not ask the wall.",
  },
  "iron-hide": {
    id: "iron-hide",
    name: "Iron Hide",
    faction: "crimson",
    type: "tactic",
    rarity: "common",
    cost: 2,
    keywords: [],
    text: "Give a friendly unit Guard and Ward.",
    target: "friendlyUnit",
    collectible: true,
    battlecry: {
      kind: "buffTarget",
      atk: 0,
      hp: 0,
      grant: ["guard", "ward"],
    },
    flavor: "Blood hardens. The next blow does not.",
  },
  "trench-harpoon": {
    id: "trench-harpoon",
    name: "Trench Harpoon",
    faction: "abyssal",
    type: "unit",
    rarity: "rare",
    cost: 3,
    attack: 3,
    health: 3,
    keywords: ["pierce"],
    text: "Pierce. Strike: deal 1 to the enemy hunter.",
    target: "none",
    collectible: true,
    strike: {
      kind: "damageEnemyHunter",
      n: 1,
    },
    flavor: "The trench throws first.",
  },
  "shell-plate": {
    id: "shell-plate",
    name: "Shell Plate",
    faction: "abyssal",
    type: "unit",
    rarity: "common",
    cost: 2,
    attack: 1,
    health: 5,
    keywords: ["guard", "retaliate"],
    text: "Guard. Retaliate.",
    target: "none",
    collectible: true,
    flavor: "Hit the plate. Pay the trench.",
  },
  "grave-warden": {
    id: "grave-warden",
    name: "Grave Warden",
    faction: "revenant",
    type: "unit",
    rarity: "rare",
    cost: 3,
    attack: 2,
    health: 5,
    keywords: ["guard", "ward"],
    text: "Guard. Ward.",
    target: "none",
    collectible: true,
    flavor: "The dead still keep the gate.",
  },
  "death-mark": {
    id: "death-mark",
    name: "Death Mark",
    faction: "revenant",
    type: "tactic",
    rarity: "common",
    cost: 2,
    keywords: [],
    text: "Give a friendly unit +2 Attack and Pierce.",
    target: "friendlyUnit",
    collectible: true,
    battlecry: {
      kind: "buffTarget",
      atk: 2,
      hp: 0,
      grant: ["pierce"],
    },
    flavor: "Once branded, the wall will not hold.",
  },
  "echo-shade": {
    id: "echo-shade",
    name: "Echo Shade",
    faction: "revenant",
    type: "unit",
    rarity: "common",
    cost: 2,
    attack: 2,
    health: 2,
    keywords: [],
    text: "Token",
    target: "none",
    collectible: false,
  },
};

export const KEYWORD_HINT: Record<Keyword, string> = {
  rush: "Can attack the turn it is played.",
  guard: "Must be attacked before the hunter or unguarded units.",
  lifesteal: "Damage this deals restores that much Health.",
  apex: "After this kills a unit, it may attack again.",
  pack: "+1 Attack while you control another Crimson unit.",
  pierce: "Can strike the hunter even if a Guard is in the way. That hit deals 2 more.",
  ward: "The first damage this unit takes is ignored.",
  retaliate: "When attacked, deal 1 extra to the attacker.",
  stalk: "Cannot be attacked or targeted until it strikes.",
  venom: "Combat damage this deals to a unit destroys that unit.",
  cleave: "When this attacks a unit, neighboring lanes take the same blow.",
  reborn: "The first time it would die, it stays in play at 1 Health.",
  frenzy: "The first time it survives damage, it can attack.",
  overwhelm: "Leftover damage from killing a unit hits the hunter.",
};

export const DECK_TITLES: Record<string, string> = {
  adamo: "Night Phalanx",
  matriarch: "Blood Pack",
  warden: "Trench Crown",
  herald: "Ash Procession",
};

export const POWER_STRIKE_NAME: Record<Faction, string> = {
  shadowborn: "Bronze Volley",
  crimson: "Pack Law",
  abyssal: "Trench Wake",
  revenant: "Ash Keep",
};

export const POWER_CINE_VIDEO: Partial<Record<Faction, string>> = {
  abyssal: "art/abyssal-power.mp4",
};

export const DECK_SIGILS: Record<Faction, string[]> = {
  shadowborn: ["first-spear", "phalanx-veteran", "spear-volley", "night-hoplite", "aegis-of-sparta"],
  crimson: ["matriarch-rex", "bonebreaker", "killing-leap", "crimson-stalker", "pack-raptor"],
  abyssal: ["abyssal-leviathan", "kraken-arm", "tide-serpent", "abyss-lurker", "leviathan-spawn"],
  revenant: ["vexed-king", "revenant-captain", "echo-shade", "vengeful-shade", "grave-warden"],
};

function expand(pairs: [string, number][]): string[] {
  const out: string[] = [];
  for (const [id, n] of pairs) for (let i = 0; i < n; i++) out.push(id);
  return out;
}

export const STARTER_DECKS: Record<string, string[]> = {
  shadowborn: expand([
    ["spear-initiate", 2],
    ["night-hoplite", 2],
    ["shadow-scout", 2],
    ["phalanx-veteran", 2],
    ["aegis-of-sparta", 2],
    ["bronze-wall", 2],
    ["spear-volley", 2],
    ["ash-wisp", 2],
    ["soul-bind", 2],
    ["grave-spearman", 2],
    ["iron-hide", 2],
    ["death-mark", 2],
    ["shell-plate", 2],
    ["trench-harpoon", 2],
    ["glowfin", 2],
    ["grave-warden", 2],
    ["hex-vengeance", 2],
    ["blood-frenzy", 2],
    ["pack-raptor", 2],
    ["tide-serpent", 2],
  ]),
  crimson: expand([
    ["blood-pup", 2],
    ["pack-raptor", 2],
    ["bonebreaker", 2],
    ["crimson-stalker", 2],
    ["blood-frenzy", 2],
    ["killing-leap", 2],
    ["iron-hide", 2],
    ["spear-initiate", 2],
    ["night-hoplite", 2],
    ["soul-bind", 2],
    ["ash-wisp", 2],
    ["shadow-scout", 2],
    ["vengeful-shade", 2],
    ["death-mark", 2],
    ["glowfin", 2],
    ["tide-serpent", 2],
    ["bronze-wall", 2],
    ["spear-volley", 2],
    ["grave-spearman", 2],
    ["hex-vengeance", 2],
  ]),
  abyssal: expand([
    ["glowfin", 2],
    ["tide-serpent", 2],
    ["abyss-lurker", 2],
    ["drown", 2],
    ["tidal-surge", 2],
    ["trench-harpoon", 2],
    ["shell-plate", 2],
    ["soul-bind", 2],
    ["ash-wisp", 2],
    ["hex-vengeance", 2],
    ["spear-initiate", 2],
    ["night-hoplite", 2],
    ["bronze-wall", 2],
    ["iron-hide", 2],
    ["death-mark", 2],
    ["grave-spearman", 2],
    ["grave-warden", 2],
    ["blood-frenzy", 2],
    ["shadow-scout", 2],
    ["vengeful-shade", 2],
  ]),
  revenant: expand([
    ["ash-wisp", 2],
    ["vengeful-shade", 2],
    ["grave-spearman", 2],
    ["soul-bind", 2],
    ["hex-vengeance", 2],
    ["grave-warden", 2],
    ["death-mark", 2],
    ["spear-initiate", 2],
    ["night-hoplite", 2],
    ["glowfin", 2],
    ["bronze-wall", 2],
    ["shell-plate", 2],
    ["iron-hide", 2],
    ["shadow-scout", 2],
    ["aegis-of-sparta", 2],
    ["blood-frenzy", 2],
    ["trench-harpoon", 2],
    ["tide-serpent", 2],
    ["pack-raptor", 2],
    ["drown", 2],
  ]),
};

export const AI_DECKS: Record<string, string[]> = {
  adamo: expand([
    ["spear-initiate", 2],
    ["night-hoplite", 2],
    ["shadow-scout", 2],
    ["phalanx-veteran", 2],
    ["umbral-blade", 2],
    ["cloaked-strategos", 2],
    ["aegis-of-sparta", 2],
    ["first-spear", 1],
    ["spear-volley", 2],
    ["bronze-wall", 2],
    ["soul-bind", 2],
    ["ash-wisp", 2],
    ["grave-spearman", 2],
    ["iron-hide", 2],
    ["death-mark", 2],
    ["shell-plate", 2],
    ["trench-harpoon", 2],
    ["glowfin", 2],
    ["grave-warden", 2],
    ["hex-vengeance", 1],
    ["pack-raptor", 2],
  ]),
  warden: expand([
    ["glowfin", 2],
    ["tide-serpent", 2],
    ["abyss-lurker", 2],
    ["kraken-arm", 2],
    ["leviathan-spawn", 2],
    ["drown", 2],
    ["tidal-surge", 2],
    ["trench-harpoon", 2],
    ["abyssal-leviathan", 1],
    ["shell-plate", 2],
    ["ash-wisp", 2],
    ["soul-bind", 2],
    ["hex-vengeance", 2],
    ["spear-initiate", 2],
    ["night-hoplite", 2],
    ["bronze-wall", 2],
    ["iron-hide", 2],
    ["death-mark", 2],
    ["grave-spearman", 2],
    ["vengeful-shade", 2],
    ["pack-raptor", 1],
  ]),
  matriarch: expand([
    ["blood-pup", 2],
    ["pack-raptor", 2],
    ["bonebreaker", 2],
    ["crimson-stalker", 2],
    ["horned-titan", 2],
    ["blood-frenzy", 2],
    ["stampede", 2],
    ["matriarch-rex", 1],
    ["killing-leap", 2],
    ["iron-hide", 2],
    ["ash-wisp", 2],
    ["spear-initiate", 2],
    ["night-hoplite", 2],
    ["soul-bind", 2],
    ["shadow-scout", 2],
    ["vengeful-shade", 2],
    ["death-mark", 2],
    ["glowfin", 2],
    ["bronze-wall", 2],
    ["grave-spearman", 2],
    ["tide-serpent", 1],
  ]),
  herald: expand([
    ["ash-wisp", 2],
    ["vengeful-shade", 2],
    ["grave-spearman", 2],
    ["revenant-captain", 2],
    ["soul-bind", 2],
    ["hex-vengeance", 2],
    ["echo-of-war", 2],
    ["vexed-king", 1],
    ["grave-warden", 2],
    ["death-mark", 2],
    ["glowfin", 2],
    ["spear-initiate", 2],
    ["night-hoplite", 2],
    ["bronze-wall", 2],
    ["shell-plate", 2],
    ["iron-hide", 2],
    ["shadow-scout", 2],
    ["aegis-of-sparta", 2],
    ["blood-frenzy", 2],
    ["tide-serpent", 2],
    ["drown", 1],
  ]),
};
export function getCard(id: string): CardDef {
  const card = CARDS[id];
  if (!card) throw new Error(`Unknown card ${id}`);
  return card;
}

export function getHunter(id: string): HunterDef {
  const hunter = HUNTERS[id];
  if (!hunter) throw new Error(`Unknown hunter ${id}`);
  return hunter;
}

export const COLLECTIBLE = Object.values(CARDS).filter((c) => c.collectible);

export function flavorOf(card: CardDef): string {
  return card.flavor ?? FACTION_META[card.faction].blurb;
}

export function cardRole(card: CardDef): "defense" | "power" | "support" {
  const k = card.keywords;
  if (k.includes("guard") || k.includes("ward") || k.includes("retaliate") || k.includes("reborn")) return "defense";
  if (
    k.includes("pierce") ||
    k.includes("rush") ||
    k.includes("apex") ||
    k.includes("venom") ||
    k.includes("cleave") ||
    k.includes("overwhelm") ||
    k.includes("frenzy") ||
    card.strike?.kind === "damageEnemyHunter" ||
    card.battlecry?.kind === "damageEnemyHunter" ||
    card.battlecry?.kind === "damageTarget" ||
    card.battlecry?.kind === "damageAllEnemyUnits"
  ) {
    return "power";
  }
  return "support";
}
